config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    "signup"  => "users#new"
  get    "signin"  => "sessions#new"
  delete "signout" => "sessions#destroy"
  get    "about"   => "static_pages#about"

  match "*path" => "application#routing_error", via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @tweet = current_user.tweets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row">
  <% if signed_in? %>
    <% provide(:title, 'Home') %>

    <div class="aside col-md-4">
      <div class="section">
        <%= render 'shared/user_info' %>
      </div>
    </div>

    <div class="col-md-8">
      <div class="timeline">
        <h2> Ztwits </h2>
        <%= render 'shared/feed' %>
      </div>
    </div>

  <% else %>
    <% provide(:title, 'Hello from Zwittur') %>

    <div class="welcome">
      <center>
        <h1> Welcome to Zwittur </h1>
        <p> Tweet zwits. Twit zwuts. Anytime. Anywhere</p>
        <%= link_to "Sign up", signup_path, class: "btn btn-primary" %>
        <%= link_to "Log in", signin_path, class: "btn btn-default" %>
      </center>
    </div>
  <% end %>
</div>