config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    "signup"  => "users#new"
  get    "signin"  => "sessions#new"
  delete "signout" => "sessions#destroy"
  get    "about"   => "static_pages#about"

  match "*path" => "application#routing_error", via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class=".alert.alert-danger">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>
          <% msg %>
        </li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="tweet">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
  <%= paginate = will_paginate @feed_items, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_feed_item.html.erb
<div class ="tweets clearfix" id="#{feed_item.id}">


  <div class="padded">
    <% if (current_user?(feed_item.user)) %>
    <%= link_to "x", feed_item, class: "tweet-actions", method: :delete,
                                                  data: { confirm: "You sure?" },
                                                  title: feed_item.content%>
    <% end %>
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <div class="user"><b><%= link_to feed_item.user.name, feed_item.user %></b></div>
    <p class="username"> @<%= feed_item.user.username %> </p>
    <div class="tweet-content"> <%= wrap(feed_item.content) %> </div>
    <p class="tweet-footer">
      <%= "Posted #{time_ago_in_words(feed_item.created_at)} ago." %> </p>

      </p>
  </div>

</div>

app/views/shared/_follow.html.erb
<%= form_for(current_user.relationships.build(following_id: @user.id)) do |f| %>

  <%= f.hidden_field :following_id %>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>

<% end %>

<!-- #= form_for(current_user.relationships.build(followed_id: @user.id)) do |f|
  div = f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-large btn-primary" -->

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user)%>

    <% if current_user.following?(@user) %>
      <%= render 'shared/unfollow' %>
    <% else %>
      <%= render 'shared/follow' %>
    <% end %>

<% end %>

app/views/shared/_profile.html.erb
<div class="profile clearfix">
  <%= link_to gravatar_for(@user, size: 52), @user %>
  <div> <%= link_to @user.name, @user %> </div>
  <div> <%= @user.email %> </div>
  <%= render 'shared/follow_form' if signed_in? %>
</div>

app/views/shared/_stats.html.erb
<div class="stats">
  <table>
    <tr>
      <th> Tweets </th>
      <th> Followings </th>
      <th> Followers </th>
    </tr>

    <tr>
      <td> <%= link_to @user.tweets.count, user_path(@user) %> </td>
      <td> <%= link_to @user.following_users.count, following_user_path(@user) %> </td>
      <td> <%= link_to @user.followers.count, followers_user_path(@user) %> </td>

    </tr>
  </table>
</div>

app/views/shared/_tweet_form.html.erb
<div class="tweet-box">
  <%= form_for(@tweet) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new Tweet..." %>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  </div>
  <% end %>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(following_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-default" %>
  <% end %>

app/views/shared/_user_info.html.erb
<% @user ||= current_user %>

<%= render 'shared/profile' %>
<%= render 'shared/stats' %>
<%= render 'shared/tweet_form' %>