config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    "signup"  => "users#new"
  get    "signin"  => "sessions#new"
  delete "signout" => "sessions#destroy"
  get    "about"   => "static_pages#about"

  match "*path" => "application#routing_error", via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <nav>
      <ul class="navbar-header">
        <li><%= link_to root_path do %>
          <img src="http://www.iconsdb.com/icons/preview/gray/twitter-xxl.png" class="logo">
          <% end %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right header-menu">
        <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", root_path %></li>
          <li><%= link_to "All zwits", tweets_path %></li>
          <li><%= link_to "Settings",  edit_user_path(current_user) %></li>
          <li><%= link_to "Sign out",  signout_path, method: "delete" %></li>
        <% else %>

           <li><%= link_to "Users", users_path %></li>
           <li><%= link_to "Log in", signin_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <%= yield %>
      </div>
    </body>
</html>